import React from 'react';
import { ArrowLeft, FileText } from 'lucide-react';

interface TermsOfServiceViewProps {
  onBack: () => void;
}

const TermsOfServiceView: React.FC<TermsOfServiceViewProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="bg-gray-900 text-white py-6 border-b border-gray-700">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <button
            onClick={onBack}
            className="flex items-center space-x-2 text-gray-400 hover:text-white mb-4 transition-colors text-sm"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>Back to Home</span>
          </button>
          <div className="flex items-center space-x-3">
            <FileText className="w-8 h-8" />
            <div>
              <h1 className="text-2xl font-bold">Terms of Service Agreement</h1>
              <p className="text-gray-400 text-xs mt-1">Last Updated: October 21, 2025 | Effective Date: October 21, 2025</p>
            </div>
          </div>
        </div>
      </div>

      {/* Content - Very Small Font, Dense Text */}
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white space-y-6 text-[10px] leading-tight text-gray-700">
          
          {/* IMPORTANT NOTICE */}
          <div className="bg-red-50 border border-red-200 p-3">
            <p className="font-bold text-red-900 text-[11px] mb-1">IMPORTANT - PLEASE READ CAREFULLY</p>
            <p className="text-[9px] text-red-800 leading-snug">
              THIS IS A LEGAL AGREEMENT BETWEEN YOU AND BA WORK XP LIMITED ("COMPANY," "WE," "US," OR "OUR"). BY CREATING AN ACCOUNT, ACCESSING, BROWSING, OR OTHERWISE USING THE BA WORK XP PLATFORM, MOBILE APPLICATIONS, WEBSITE, SERVICES, OR ANY CONTENT PROVIDED THEREIN (COLLECTIVELY, THE "SERVICES"), YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE (THE "TERMS" OR "AGREEMENT") AND OUR PRIVACY POLICY, WHICH IS INCORPORATED HEREIN BY REFERENCE. IF YOU DO NOT AGREE TO THESE TERMS IN THEIR ENTIRETY, YOU ARE NOT AUTHORIZED TO USE THE SERVICES AND MUST IMMEDIATELY CEASE ALL ACCESS. YOUR CONTINUED USE OF THE SERVICES CONSTITUTES YOUR BINDING ACCEPTANCE OF THESE TERMS AS THEY MAY BE AMENDED FROM TIME TO TIME.
            </p>
          </div>

          {/* 1. DEFINITIONS AND INTERPRETATION */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">1. DEFINITIONS AND INTERPRETATION</h2>
            <div className="space-y-1 ml-2">
              <p>1.1 In these Terms, unless the context otherwise requires, the following definitions shall apply:</p>
              <p className="ml-3">(a) <strong>"Account"</strong> means the user account created by you to access and use the Services, including all associated credentials, data, and content;</p>
              <p className="ml-3">(b) <strong>"Content"</strong> means all materials, information, data, text, software, music, sound, photographs, graphics, video, messages, tags, interactive features, AI-generated content, course materials, training modules, and other materials available through the Services, whether publicly posted or privately transmitted;</p>
              <p className="ml-3">(c) <strong>"Device"</strong> means any computer, mobile phone, tablet, or other electronic device used to access the Services;</p>
              <p className="ml-3">(d) <strong>"Intellectual Property Rights"</strong> means all patents, rights to inventions, utility models, copyright and related rights, trademarks, service marks, trade, business and domain names, rights in trade dress or get-up, rights in goodwill or to sue for passing off, unfair competition rights, rights in designs, rights in computer software, database rights, topography rights, moral rights, rights in confidential information (including know-how and trade secrets) and any other intellectual property rights, in each case whether registered or unregistered and including all applications for and renewals or extensions of such rights, and all similar or equivalent rights or forms of protection in any part of the world;</p>
              <p className="ml-3">(e) <strong>"Personal Data"</strong> means any information relating to an identified or identifiable natural person as defined under applicable data protection laws;</p>
              <p className="ml-3">(f) <strong>"Subscription"</strong> means your paid access to the Services for a specified period as detailed in Section 5;</p>
              <p className="ml-3">(g) <strong>"User Content"</strong> means any content, materials, or information that you submit, upload, post, or transmit through the Services;</p>
              <p className="ml-3">(h) <strong>"User"</strong>, <strong>"you"</strong>, or <strong>"your"</strong> refers to the individual accessing or using the Services, or the company or legal entity on whose behalf such individual is accessing or using the Services.</p>
              <p className="mt-2">1.2 References to "including" or "include" or "in particular" shall be construed as being by way of illustration or emphasis only and shall not be construed as, nor shall they take effect as, limiting the generality of any preceding words.</p>
              <p>1.3 Headings are for convenience only and do not affect the interpretation of these Terms.</p>
              <p>1.4 A reference to a statute or statutory provision includes a reference to: (a) that statute or provision as amended, extended, re-enacted, or consolidated from time to time; and (b) any subordinate legislation made under that statute or statutory provision.</p>
            </div>
          </section>

          {/* 2. ACCEPTANCE OF TERMS */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">2. ACCEPTANCE OF TERMS AND CONDITIONS</h2>
            <div className="space-y-1 ml-2">
              <p>2.1 By clicking "I Accept," "Sign Up," "Register," or any similar button, or by accessing, downloading, or using the Services in any manner whatsoever, you expressly acknowledge and agree that: (a) you have carefully read and fully understand these Terms in their entirety; (b) you have had sufficient opportunity to seek independent legal advice regarding these Terms; (c) you voluntarily and unconditionally agree to be legally bound by these Terms; and (d) you waive any right to claim that you did not read, understand, or have the opportunity to review these Terms prior to acceptance.</p>
              <p>2.2 These Terms constitute the entire agreement between you and the Company with respect to your use of the Services and supersede all prior or contemporaneous understandings, agreements, representations, and warranties, whether written or oral, with respect to the Services.</p>
              <p>2.3 The Company reserves the absolute right, in its sole and unfettered discretion, to refuse service, terminate Accounts, remove or edit Content, or cancel Subscriptions at any time, for any reason or no reason, with or without prior notice, and without liability to you or any third party.</p>
              <p>2.4 If any provision of these Terms is found to be unenforceable or invalid under any applicable law, such unenforceability or invalidity shall not render these Terms unenforceable or invalid as a whole. Such provisions shall be deleted without affecting the remaining provisions herein, and the parties agree that the provision shall be reformed to the minimum extent necessary to make such provision valid, legal, and enforceable while preserving the original intent.</p>
            </div>
          </section>

          {/* 3. ELIGIBILITY AND REGISTRATION */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">3. ELIGIBILITY REQUIREMENTS AND ACCOUNT REGISTRATION</h2>
            <div className="space-y-1 ml-2">
              <p>3.1 <strong>Age Requirement:</strong> You must be at least sixteen (16) years of age to register for an Account or use the Services. By registering, you represent and warrant that you are at least 16 years old. If you are under 18, you represent and warrant that you have obtained verifiable parental or legal guardian consent to enter into this Agreement. The Company reserves the right, in its sole discretion, to request proof of age or parental consent at any time. Failure to provide such proof within 7 days of request shall result in immediate Account suspension.</p>
              <p>3.2 <strong>Capacity:</strong> You represent and warrant that: (a) you have the legal capacity and authority to enter into this Agreement; (b) you are not barred or otherwise legally prohibited from accessing or using the Services under the laws of the jurisdiction in which you reside or from which you access the Services; (c) you will comply with all applicable local, state, national, and international laws, regulations, and treaties; and (d) you have not been previously suspended or removed from the Services.</p>
              <p>3.3 <strong>Account Information:</strong> When registering for an Account, you agree to: (a) provide accurate, current, and complete information as prompted by the registration form ("Registration Data"); (b) maintain and promptly update the Registration Data to keep it accurate, current, and complete; (c) maintain the security and confidentiality of your Account password and identification; (d) notify the Company immediately of any unauthorized use of your Account or any other breach of security; and (e) accept all responsibility for any and all activities that occur under your Account, whether or not you have authorized such activities. You acknowledge and agree that the Company may rely on your Registration Data when making decisions regarding your Account, including but not limited to identity verification, payment processing, customer support, and enforcement actions.</p>
              <p>3.4 <strong>Account Security:</strong> You are solely responsible for maintaining the confidentiality of your Account credentials (including username, password, and any other security information). You agree not to: (a) share your Account credentials with any third party; (b) use another person's Account at any time; (c) allow your Account to be used by any person other than yourself; or (d) do anything that might jeopardize the security of your Account. The Company cannot and will not be liable for any loss or damage arising from your failure to comply with these security obligations. You agree to immediately notify the Company of any unauthorized use of your Account or any other security breach of which you become aware.</p>
              <p>3.5 <strong>Business and Corporate Accounts:</strong> If you are registering for an Account on behalf of a company, organization, or other legal entity, you represent and warrant that you have the authority to bind such entity to these Terms, and the terms "you" and "your" shall refer to such entity. In such cases, you personally guarantee compliance with these Terms and accept personal liability for any breaches.</p>
            </div>
          </section>

          {/* 4. ACCOUNT SHARING PROHIBITION - CRITICAL */}
          <section className="bg-red-50 border-l-4 border-red-600 pl-3 py-2">
            <h2 className="font-bold text-red-900 text-[11px] mb-2 uppercase">4. PROHIBITION OF ACCOUNT SHARING (MATERIAL TERM)</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>4.1 <strong>SINGLE-USER LICENSE:</strong> Each Account is licensed for use by ONE (1) individual user only. This is a material term of this Agreement, and any breach constitutes a fundamental violation entitling the Company to immediate termination and all available remedies.</p>
              <p>4.2 <strong>PROHIBITED CONDUCT:</strong> You expressly agree that you SHALL NOT, under any circumstances: (a) share, transfer, sell, rent, lease, lend, or otherwise provide access to your Account credentials to any other person or entity, whether for compensation or gratuitously; (b) allow any third party to access your Account, whether in your presence or absence; (c) create multiple Accounts for the same individual; (d) use a VPN, proxy, or any other technology to obscure your identity or location with the intent to circumvent our security measures; (e) attempt to decompile, reverse engineer, or otherwise discover the source code or underlying algorithms of our device-binding technology; (f) pool, share, or time-share access to your Account among multiple users; (g) create "group accounts" or "shared accounts" for multiple users; or (h) permit any family member, friend, colleague, classmate, or other person to access your Account under any circumstances whatsoever.</p>
              <p>4.3 <strong>MONITORING AND DETECTION:</strong> The Company employs sophisticated technological measures to detect Account sharing, including but not limited to: (a) hardware-based device fingerprinting using CPU identifiers, GPU characteristics, screen resolution, installed fonts, and system configuration; (b) IP address tracking and geolocation analysis; (c) behavioral analysis including usage patterns, session duration, login frequency, feature utilization, and interaction timing; (d) machine learning algorithms that identify anomalous access patterns; (e) browser fingerprinting; and (f) real-time monitoring of concurrent sessions. You acknowledge and consent to such monitoring and agree that detection of Account sharing by our automated systems shall constitute prima facie evidence of violation, which may be relied upon for enforcement purposes without further investigation.</p>
              <p>4.4 <strong>THREE-STRIKE ENFORCEMENT POLICY:</strong></p>
              <p className="ml-3"><strong>First Violation:</strong> Upon first detected violation, the Company shall: (a) immediately suspend your Account for a minimum of 24 hours; (b) send written notice to your registered email address detailing the violation; (c) require you to acknowledge the violation and confirm understanding of this Policy before reactivating your Account; (d) permanently log the violation in your Account history; and (e) reset your device binding, requiring re-registration from your primary device. No refund or credit shall be issued for the suspension period. You will receive one (1) warning only.</p>
              <p className="ml-3"><strong>Second Violation:</strong> Upon second detected violation, the Company shall: (a) immediately suspend your Account for a minimum of seven (7) calendar days; (b) issue a final written warning via registered email; (c) require completion of mandatory training on Account security and Terms compliance; (d) implement enhanced monitoring on your Account for a minimum of 90 days; (e) void any promotional pricing, discounts, or special offers applied to your Subscription; and (f) reserve the right to require payment of an Account reinstatement fee of £50 before reactivation. No refund shall be issued for the suspension period or any other amounts paid.</p>
              <p className="ml-3"><strong>Third Violation:</strong> Upon third detected violation or any subsequent violation, the Company shall, without any further warning or notice: (a) IMMEDIATELY AND PERMANENTLY TERMINATE your Account and all associated Services; (b) PERMANENTLY BAN you from creating any future Accounts or accessing the Services under any circumstances; (c) FORFEIT all remaining Subscription time without refund; (d) DENY all future requests for Account reinstatement, appeals, or reconsideration; (e) BLACKLIST your payment methods, email addresses, and device identifiers to prevent future registration; and (f) DENY ALL CUSTOMER SUPPORT for any matter related to your terminated Account. This termination is ABSOLUTE, IRREVERSIBLE, and FINAL. No exceptions will be made under any circumstances. No partial refunds, pro-rata credits, or compensation of any kind will be provided.</p>
              <p>4.5 <strong>NO SUPPORT AFTER PERMANENT TERMINATION:</strong> Upon permanent termination under Section 4.4(c), the Company shall have NO OBLIGATION WHATSOEVER to provide you with any customer support, technical assistance, Account data, export of User Content, explanation of termination reasons beyond the violation of this Section 4, appeals process, or any other form of assistance. All customer support requests, emails, and communications from terminated users shall be automatically ignored and discarded without response.</p>
              <p>4.6 <strong>CUMULATIVE VIOLATIONS:</strong> Violations under this Section 4 are cumulative and permanent. They do not reset or expire, regardless of the passage of time. A violation that occurred on your first day of Subscription shall be counted toward the three-strike limit even if it occurred years prior.</p>
              <p>4.7 <strong>ADDITIONAL REMEDIES:</strong> The remedies set forth in this Section 4 are not exclusive. The Company reserves all rights to pursue any and all additional legal remedies available under applicable law, including but not limited to: (a) civil litigation for breach of contract; (b) injunctive relief; (c) recovery of all amounts owed plus interest, collection costs, and attorneys' fees; (d) reporting of fraudulent activity to payment processors and financial institutions; and (e) cooperation with law enforcement authorities if criminal activity is suspected.</p>
            </div>
          </section>

          {/* 5. DEVICE BINDING TECHNOLOGY */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">5. DEVICE BINDING AND AUTHENTICATION TECHNOLOGY</h2>
            <div className="space-y-1 ml-2">
              <p>5.1 <strong>Device Registration:</strong> Upon your first successful login, your Account shall be automatically and permanently bound to the specific Device from which you accessed the Services (the "Registered Device"). This binding is based on a unique hardware fingerprint generated from your Device's physical characteristics, including but not limited to: processor identifiers, graphics card specifications, motherboard serial numbers, installed hardware components, and system configuration. This fingerprint is cryptographically hashed and stored securely.</p>
              <p>5.2 <strong>Browser Flexibility:</strong> You may access your Account from multiple web browsers (e.g., Google Chrome, Mozilla Firefox, Apple Safari, Microsoft Edge, Brave) installed on your Registered Device without triggering a security violation. Our system recognizes that multiple browsers on the same physical Device represent legitimate single-user access.</p>
              <p>5.3 <strong>Cross-Device Prohibition:</strong> You MAY NOT access your Account from any Device other than your Registered Device. This prohibition includes but is not limited to: (a) accessing from a different laptop or desktop computer; (b) accessing from a mobile phone or tablet; (c) accessing from a work computer if your Account was registered on a personal computer, or vice versa; (d) accessing from a friend's, family member's, colleague's, or any other person's Device; (e) accessing from public computers, internet cafes, libraries, or shared workstations; or (f) accessing from virtual machines, cloud computing instances, or remote desktop services. Any attempt to access your Account from a non-Registered Device shall immediately trigger our security systems and result in automatic Account suspension and potential termination as described in Section 4.</p>
              <p>5.4 <strong>Device Change Requests:</strong> If you have legitimately purchased a new Device and wish to transfer your Account binding, you must: (a) submit a formal Device Change Request via email to support@baworkxp.com with subject line "Device Change Request - [Your Account Email]"; (b) provide photographic proof of Device ownership including serial numbers, purchase receipts, or other documentation establishing legitimate ownership; (c) provide a detailed written explanation of why the Device change is necessary; (d) complete identity verification procedures as required by the Company, which may include government-issued ID, video verification, or answering security questions; (e) pay a Device Change Processing Fee of £25 (non-refundable); and (f) wait 5-10 business days for manual review and approval. The Company reserves absolute discretion to approve or deny any Device Change Request for any reason or no reason. Frequent Device Change Requests (more than twice per year) may result in Account review, enhanced monitoring, Subscription price increases, or permanent Account termination.</p>
              <p>5.5 <strong>No Workarounds:</strong> Any attempt to circumvent, disable, manipulate, or interfere with our device-binding technology, including but not limited to using hardware emulators, virtual machines, device spoofing software, VPNs with device masking, or any other technical means, shall constitute a material breach of these Terms and grounds for immediate permanent termination without refund, in addition to potential legal action for computer fraud under applicable laws.</p>
              <p>5.6 <strong>Consent to Monitoring:</strong> By accepting these Terms, you explicitly consent to the Company's collection, processing, and storage of your Device's hardware fingerprint, system configuration, IP addresses, geolocation data, and usage patterns for the purposes of enforcing these Terms and preventing Account sharing. This consent is irrevocable for the duration of your Subscription. You acknowledge that such monitoring may be conducted in real-time, continuously, and without further notice to you.</p>
            </div>
          </section>

          {/* 6. SUBSCRIPTION TERMS */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">6. SUBSCRIPTION TERMS, PRICING, AND ACCESS PERIOD</h2>
            <div className="space-y-1 ml-2">
              <p>6.1 <strong>Subscription Period:</strong> Upon payment of the applicable Subscription fee, you shall receive access to the Services for a fixed term of one hundred eighty (180) calendar days (approximately six months) commencing on the date of successful payment processing (the "Subscription Period"). The Subscription Period is non-extendable and non-transferable. No partial month Subscriptions are available.</p>
              <p>6.2 <strong>No Automatic Renewal:</strong> Your Subscription will NOT automatically renew at the end of the Subscription Period. Upon expiration, your access to all Services, Content, and User Content shall immediately and permanently cease. You will receive email notifications at 30 days, 14 days, 7 days, and 1 day prior to expiration, reminding you to renew if you wish to continue access. Failure to renew constitutes voluntary termination of your Account.</p>
              <p>6.3 <strong>Renewal Process:</strong> To renew your Subscription after expiration, you must: (a) log in to your Account (if still active) or contact support@baworkxp.com; (b) make full payment of the then-current Subscription fee (see Section 6.4 regarding price changes); (c) confirm acceptance of the then-current Terms of Service; and (d) complete any additional verification or security procedures required by the Company. Renewal is not guaranteed and may be denied at the Company's sole discretion, including but not limited to cases involving prior Terms violations, payment disputes, or abuse of Services.</p>
              <p>6.4 <strong>Pricing and Payment:</strong></p>
              <p className="ml-3">(a) <strong>Current Pricing:</strong> As of the Last Updated date shown above, the Subscription fees are: (i) Free Trial Tier: £0.00 - Limited access to one (1) project only, restricted features, intended for evaluation purposes only, subject to immediate termination without notice; (ii) Premium Tier: £300.00 per 180-day Subscription Period - Full access to five (5) projects, all platform features including AI stakeholders, voice meetings, transcript meetings, practice modules, guided learning, Agile tools, and customer support; (iii) Enterprise Tier: Custom pricing negotiated on a case-by-case basis - Unlimited projects, priority support, service level agreements (SLAs), custom integrations, API access, dedicated account manager, and volume licensing options.</p>
              <p className="ml-3">(b) <strong>Currency:</strong> All prices are stated and charged in British Pounds Sterling (£ GBP). If you are paying from a non-UK jurisdiction, your payment processor or financial institution may apply currency conversion rates and foreign transaction fees, for which the Company shall not be responsible.</p>
              <p className="ml-3">(c) <strong>Payment Methods:</strong> We accept payment via major credit cards (Visa, Mastercard, American Express), debit cards, PayPal, and other payment methods as displayed at checkout. By providing payment information, you represent and warrant that: (i) you are authorized to use the payment method provided; (ii) all payment information is accurate and current; (iii) you will promptly update your payment information if it changes; and (iv) you authorize the Company to charge the payment method for all applicable fees.</p>
              <p className="ml-3">(d) <strong>Price Changes:</strong> The Company reserves the right to change Subscription fees at any time, with or without prior notice, in its sole and absolute discretion. Price changes shall apply to: (i) all new Subscriptions purchased after the effective date of the price change; and (ii) Subscription renewals, even for existing customers. Active Subscriptions that have already been paid for shall continue at the original price until expiration. You acknowledge and agree that Subscription fees may increase substantially between your initial Subscription and any renewal, and you shall have no right to claim continuation of prior pricing. If you disagree with a price increase, your sole remedy is to not renew your Subscription.</p>
              <p className="ml-3">(e) <strong>Taxes:</strong> The Subscription fees stated do not include any taxes, levies, duties, or similar governmental assessments of any nature, including value-added tax (VAT), goods and services tax (GST), sales tax, use tax, or withholding taxes (collectively, "Taxes"). You are responsible for paying all Taxes associated with your purchase, except for taxes based on the Company's net income. If the Company is legally required to collect or pay Taxes for which you are responsible, such Taxes will be invoiced to you and you agree to pay such amounts unless you provide the Company with a valid tax exemption certificate authorized by the appropriate taxing authority.</p>
              <p className="ml-3">(f) <strong>Payment Disputes and Chargebacks:</strong> If you initiate a chargeback, payment dispute, or reversal through your payment processor or financial institution (collectively, a "Payment Dispute"), the Company shall: (i) immediately suspend or terminate your Account pending resolution; (ii) investigate the matter and provide evidence to the payment processor or financial institution as appropriate; (iii) if the Payment Dispute is found in the Company's favor, reinstate your Account only upon payment of all outstanding amounts plus a Payment Dispute Processing Fee of £50; and (iv) if you initiate fraudulent or unjustified Payment Disputes, permanently terminate your Account, blacklist your payment methods, and pursue all available legal remedies including but not limited to recovery of fees, costs, and damages. THE PROPER METHOD TO REQUEST A REFUND IS THROUGH THE PROCESS DESCRIBED IN SECTION 7, NOT THROUGH A PAYMENT DISPUTE. INITIATING A PAYMENT DISPUTE WHEN A REFUND REQUEST SHOULD HAVE BEEN MADE CONSTITUTES A BREACH OF THESE TERMS.</p>
              <p>6.5 <strong>Project Limits by Tier:</strong> Your access to projects is limited based on your Subscription tier: (a) Free Trial: One (1) project selection only, permanently locked after selection, no ability to switch projects; (b) Premium: Five (5) projects accessible throughout your Subscription Period, ability to switch between projects freely; (c) Enterprise: Unlimited project access. These limits are strictly enforced by the platform and cannot be exceeded regardless of circumstances.</p>
              <p>6.6 <strong>No Pro-Rata Refunds:</strong> Subscription fees are non-refundable except as expressly provided in Section 7. There shall be no pro-rata, partial, or proportional refunds under any circumstances, including but not limited to: early termination, reduced usage, dissatisfaction with Services, technical difficulties, Account suspension, or any other reason not explicitly covered by Section 7. By purchasing a Subscription, you acknowledge and agree that you are committing to the full Subscription Period and fee.</p>
            </div>
          </section>

          {/* 7. REFUND POLICY */}
          <section className="bg-yellow-50 border-l-4 border-yellow-600 pl-3 py-2">
            <h2 className="font-bold text-yellow-900 text-[11px] mb-2 uppercase">7. REFUND AND CANCELLATION POLICY (TIME-SENSITIVE)</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>7.1 <strong>14-Day Refund Window:</strong> Subject to the conditions and procedures set forth in this Section 7, you may request a full refund of your Subscription fee if, and only if: (a) the refund request is submitted via email to support@baworkxp.com within fourteen (14) calendar days of your original purchase date (the "Refund Window"); (b) you provide your full name, Account email address, and order/transaction ID in your refund request; (c) your Account has not been suspended or terminated for violations of these Terms, including but not limited to Account sharing; (d) you have not initiated a Payment Dispute, chargeback, or payment reversal; (e) you respond to any verification emails or requests for information from the Company within 48 hours; and (f) you have not previously requested and received a refund for this or any prior Subscription (repeat refund requests are prohibited and constitute abuse).</p>
              <p>7.2 <strong>Refund Request Procedure:</strong> To request a refund within the Refund Window, you must: (a) send an email to support@baworkxp.com with the subject line "Refund Request - [Your Account Email] - [Order ID]"; (b) include in the email body: (i) your full name as it appears on the Account; (ii) the email address associated with your Account; (iii) the transaction ID or order number from your payment confirmation; (iv) the date of purchase; (v) the payment method used (last 4 digits of card or PayPal email); and (vi) optionally, a brief reason for the refund request (not required but helpful for our records); (c) respond promptly to any verification questions or requests for additional information from our support team; and (d) allow 5-10 business days for review and processing. Refund requests that do not follow this exact procedure may be delayed or denied.</p>
              <p>7.3 <strong>Refund Processing:</strong> If your refund request is approved: (a) you will receive an email confirmation of approval within 5-10 business days; (b) your Account access will be immediately and permanently revoked upon approval; (c) the refund amount will be credited to the original payment method used for purchase; (d) refund processing time depends on your payment processor and may take 5-10 business days after approval to appear in your account; (e) if your original payment method is no longer valid, you must provide an alternative refund method acceptable to the Company; (f) refund amounts shall be in the same currency as the original purchase; (g) any currency conversion fees, foreign transaction fees, or payment processing fees incurred during the original purchase are non-refundable and will be deducted from the refund amount; and (h) you shall receive a refund receipt via email for your records.</p>
              <p>7.4 <strong>ABSOLUTE NO-REFUND POLICY AFTER 14 DAYS:</strong> AFTER THE EXPIRATION OF THE 14-DAY REFUND WINDOW, ALL SUBSCRIPTION FEES ARE FINAL, NON-REFUNDABLE, AND NON-REVERSIBLE UNDER ANY AND ALL CIRCUMSTANCES. This no-refund policy applies without exception, regardless of: (a) level of usage or non-usage of the Services; (b) dissatisfaction with the Services, Content, features, or any aspect thereof; (c) technical difficulties, bugs, errors, or platform downtime; (d) changes to these Terms or the Services; (e) personal circumstances such as financial hardship, medical issues, or other life events; (f) Your inability to access the Services due to Device loss, theft, or malfunction; (g) migration to a competing platform or service; (h) completion of your learning objectives before the end of the Subscription Period; (i) Account suspension or termination for violations of these Terms; (j) force majeure events or circumstances beyond the Company's control; or (k) any other reason whatsoever, whether foreseeable or unforeseeable at the time of purchase. BY PURCHASING A SUBSCRIPTION, YOU EXPLICITLY ACKNOWLEDGE AND AGREE TO THIS ABSOLUTE NO-REFUND POLICY AND WAIVE ANY RIGHT TO DISPUTE CHARGES OR REQUEST REFUNDS AFTER THE 14-DAY WINDOW HAS CLOSED.</p>
              <p>7.5 <strong>Cancellation Without Refund:</strong> You may cancel your Subscription at any time by sending an email to support@baworkxp.com with "Cancellation Request" in the subject line. However: (a) if the cancellation is requested within the 14-day Refund Window and you meet all eligibility criteria in Section 7.1, you will receive a full refund and immediate access termination; (b) if the cancellation is requested after the 14-day Refund Window, NO REFUND shall be issued under any circumstances, but your access to the Services shall continue until the natural expiration date of your current Subscription Period; (c) upon cancellation after 14 days, you remain bound by all Terms herein for the remainder of your Subscription Period; (d) cancelled Subscriptions will not automatically renew; and (e) you may not "un-cancel" a cancellation once submitted, and any request to continue your Subscription beyond the current period will be treated as a new purchase subject to then-current pricing.</p>
              <p>7.6 <strong>Refund Abuse Prevention:</strong> The Company employs sophisticated fraud detection systems to identify and prevent refund abuse. Conduct constituting refund abuse includes but is not limited to: (a) making repeated purchases and refund requests across multiple Accounts or payment methods; (b) requesting refunds after consuming substantial amounts of Content or completing significant portions of the learning curriculum; (c) using the 14-day refund policy as a "free trial" mechanism with intent to refund; (d) sharing Accounts during the refund period and then requesting a refund; (e) providing false or misleading information in refund requests; or (f) initiating Payment Disputes instead of following the proper refund request procedure. If the Company determines, in its sole discretion, that you have engaged in refund abuse, you shall be: (i) permanently banned from all current and future use of the Services; (ii) blacklisted from making any future purchases; (iii) denied the requested refund; (iv) required to pay all amounts owed plus interest and collection costs; and (v) potentially reported to payment processors, credit bureaus, and law enforcement authorities.</p>
            </div>
          </section>

          {/* 8. USER CONDUCT AND ACCEPTABLE USE */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">8. USER CONDUCT, ACCEPTABLE USE, AND PROHIBITED ACTIVITIES</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>8.1 <strong>General Conduct Standards:</strong> You agree to use the Services in a manner consistent with all applicable laws, regulations, and these Terms. You agree to conduct yourself professionally, respectfully, and ethically when using the Services and interacting with other users, our AI systems, and our staff.</p>
              <p>8.2 <strong>Prohibited Conduct:</strong> You SHALL NOT engage in any of the following activities:</p>
              <p className="ml-3">(a) <strong>Account Abuse:</strong> Sharing account credentials, creating multiple accounts for the same individual, allowing unauthorized access to your Account, impersonating another person or entity, or misrepresenting your affiliation with any person or entity;</p>
              <p className="ml-3">(b) <strong>Content Violations:</strong> Uploading, posting, transmitting, or distributing any content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, racially or ethnically offensive, or otherwise objectionable;</p>
              <p className="ml-3">(c) <strong>Intellectual Property Infringement:</strong> Copying, reproducing, distributing, modifying, creating derivative works from, publicly displaying, publicly performing, republishing, downloading, storing, or transmitting any Content except as expressly permitted under these Terms; infringing or misappropriating any intellectual property rights, publicity rights, or privacy rights of any third party;</p>
              <p className="ml-3">(d) <strong>Security Violations:</strong> Attempting to gain unauthorized access to any portion of the Services, other Accounts, computer systems, or networks connected to the Services through hacking, password mining, brute force attacks, or any other means; probing, scanning, or testing the vulnerability of the Services or any network connected to the Services; breaching or circumventing any security or authentication measures; accessing or searching the Services by any means other than our publicly supported interfaces;</p>
              <p className="ml-3">(e) <strong>System Abuse:</strong> Using any robot, spider, scraper, crawler, or other automated means to access the Services for any purpose; interfering with or disrupting the integrity or performance of the Services or the data contained therein; introducing viruses, malware, worms, Trojan horses, or other harmful code; attempting to decipher, decompile, disassemble, or reverse engineer any of the software or algorithms comprising the Services;</p>
              <p className="ml-3">(f) <strong>Spam and Unsolicited Communications:</strong> Sending unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of solicitation; harvesting or collecting email addresses, user IDs, or other user information; using the Services to send bulk, commercial, or promotional messages;</p>
              <p className="ml-3">(g) <strong>Fraudulent Activity:</strong> Providing false, inaccurate, misleading, or fraudulent information during registration or at any other time; engaging in fraudulent schemes, scams, or deceptive practices; initiating chargebacks or payment disputes in bad faith; attempting to defraud the Company, other users, or any third party;</p>
              <p className="ml-3">(h) <strong>Commercial Exploitation:</strong> Reselling, sublicensing, or otherwise commercializing access to the Services without express written permission; using the Services for any commercial purpose not expressly authorized by these Terms; offering to sell or selling any portion of the Services, Content, or Accounts;</p>
              <p className="ml-3">(i) <strong>Competitive Use:</strong> Using the Services to develop, support, or market a competing product or service; benchmarking the Services against competitors without written permission; copying features, functionality, or Content to create competitive offerings;</p>
              <p className="ml-3">(j) <strong>System Overload:</strong> Sending excessive requests to our servers that could burden, impair, or disable the Services; engaging in denial-of-service (DoS) or distributed denial-of-service (DDoS) attacks;</p>
              <p className="ml-3">(k) <strong>Legal Violations:</strong> Using the Services to violate any applicable law, statute, ordinance, or regulation; using the Services for any illegal or unauthorized purpose; facilitating or encouraging any violations of these Terms or applicable laws.</p>
              <p>8.3 <strong>Spam Policy:</strong> We maintain a strict anti-spam policy. You agree not to use the Services to send unsolicited bulk communications of any kind. This includes but is not limited to: unsolicited commercial email (UCE), bulk email, mass mailing, "junk mail," "chain letters," or any other type of unsolicited message. Violation of this anti-spam policy will result in immediate Account termination without refund. We reserve the right to report spam activities to relevant authorities and internet service providers.</p>
              <p>8.4 <strong>Monitoring and Enforcement:</strong> The Company reserves the right, but has no obligation, to monitor, review, or moderate User Content, Account activity, and use of the Services for compliance with these Terms. We may investigate violations, collect evidence, and cooperate with law enforcement authorities. We may take any action we deem appropriate in response to violations, including but not limited to: warning users, suspending or terminating Accounts, removing or editing Content, reporting to authorities, and pursuing legal action.</p>
              <p>8.5 <strong>Consequences of Violations:</strong> Violation of this Section 8 may result in: (a) immediate temporary or permanent suspension or termination of your Account without refund; (b) removal of your Content; (c) forfeiture of all fees paid; (d) legal action including civil litigation and criminal prosecution; (e) referral to law enforcement or regulatory authorities; (f) cooperation with third parties in investigating violations; and (g) any other remedies available at law or in equity.</p>
            </div>
          </section>

          {/* 9. AI SERVICES AND USER RESPONSIBILITY */}
          <section className="bg-blue-50 border-l-4 border-blue-600 pl-3 py-2">
            <h2 className="font-bold text-blue-900 text-[11px] mb-2 uppercase">9. AI-POWERED SERVICES, INPUT AND OUTPUT RESPONSIBILITY</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>9.1 <strong>AI Services Description:</strong> The Services include various artificial intelligence (AI) and machine learning features, including but not limited to: AI-powered virtual stakeholders for practice conversations, natural language processing for transcript generation and analysis, voice synthesis and speech-to-text conversion, automated feedback and coaching, content recommendations, and other AI-assisted functionalities (collectively, "AI Services").</p>
              <p>9.2 <strong>Input Responsibility:</strong> You are solely and exclusively responsible for all information, data, text, prompts, queries, instructions, and other content that you input, upload, submit, or provide to the AI Services ("Input"). You represent and warrant that: (a) you have all necessary rights, licenses, and permissions to provide the Input; (b) the Input does not infringe, misappropriate, or violate any third party's intellectual property rights, privacy rights, publicity rights, or any other rights; (c) the Input does not contain any illegal, harmful, threatening, abusive, harassing, defamatory, obscene, or otherwise objectionable material; (d) the Input does not contain any viruses, malware, or other harmful code; and (e) you have obtained all necessary consents from individuals whose personal data is included in the Input. YOU ACKNOWLEDGE THAT THE COMPANY HAS NO OBLIGATION TO MONITOR, REVIEW, OR VERIFY YOUR INPUT AND ASSUMES NO RESPONSIBILITY OR LIABILITY FOR YOUR INPUT.</p>
              <p>9.3 <strong>Output Responsibility and Limitations:</strong></p>
              <p className="ml-3">(a) <strong>Your Responsibility for Output:</strong> All content, responses, suggestions, recommendations, transcripts, and other materials generated by the AI Services based on your Input ("Output") are provided to you for your use. YOU ARE SOLELY RESPONSIBLE FOR REVIEWING, EVALUATING, VERIFYING, AND DETERMINING THE APPROPRIATENESS, ACCURACY, AND SUITABILITY OF ALL OUTPUT BEFORE USING IT FOR ANY PURPOSE. You agree not to use Output without your own independent review and judgment.</p>
              <p className="ml-3">(b) <strong>No Guarantee of Accuracy:</strong> AI Services use advanced machine learning algorithms but are not perfect. Output may contain errors, inaccuracies, omissions, inconsistencies, biases, or inappropriate content. THE COMPANY MAKES NO WARRANTIES OR REPRESENTATIONS REGARDING THE ACCURACY, COMPLETENESS, RELIABILITY, CURRENTNESS, OR QUALITY OF ANY OUTPUT. Output should be treated as suggestions only and not as professional advice.</p>
              <p className="ml-3">(c) <strong>Not Professional Advice:</strong> Output from AI Services does not constitute professional advice (legal, financial, medical, career, or otherwise). You should not rely on Output as a substitute for professional consultation with qualified experts. If you require professional advice, you should consult with a licensed professional in the relevant field.</p>
              <p className="ml-3">(d) <strong>Use at Your Own Risk:</strong> You use Output at your own risk. You agree to independently verify any Output before relying on it for any purpose, including in your professional work, academic submissions, job applications, or business decisions.</p>
              <p>9.4 <strong>Data Usage for AI Training:</strong> You acknowledge and consent that Input and Output may be used by the Company to train, improve, and enhance our AI models, algorithms, and Services. This may include but is not limited to: analyzing patterns, generating training datasets, improving accuracy, reducing biases, and developing new features. All such use will be in compliance with our Privacy Policy. If you do not wish your data to be used for AI training, contact support@baworkxp.com, but note that this may limit or prevent your use of certain AI Services.</p>
              <p>9.5 <strong>No Ownership of Output:</strong> As between you and the Company, and to the extent permitted by law, you own the Input you provide and the Output you receive. However, the Company retains all rights, title, and interest in the underlying AI models, algorithms, software, and technology used to generate Output. You may use Output for your personal, educational, and professional purposes consistent with these Terms, but you may not use Output to train competing AI models or develop competing services.</p>
              <p>9.6 <strong>AI Service Availability:</strong> AI Services rely on third-party AI service providers and may be subject to the terms, conditions, usage limits, and availability of such providers. The Company reserves the right to modify, suspend, discontinue, or replace AI Services at any time without notice due to provider changes, cost considerations, or for any other reason. We are not liable for any disruption to AI Services caused by third-party providers.</p>
              <p>9.7 <strong>Prohibited AI Uses:</strong> You agree not to: (a) use AI Services to generate illegal, harmful, misleading, or deceptive content; (b) attempt to reverse engineer, extract, or steal our AI models or training data; (c) use Output to create competing AI services; (d) submit Input designed to manipulate, jailbreak, or circumvent AI safety measures; (e) use AI Services for automated bulk content generation for commercial purposes; or (f) use AI Services in any manner that violates third-party AI provider policies.</p>
            </div>
          </section>

          {/* 10. INTELLECTUAL PROPERTY */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">10. INTELLECTUAL PROPERTY RIGHTS AND LICENSES</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>10.1 <strong>Company Ownership:</strong> All Content, features, functionality, designs, interfaces, information, software, code, databases, APIs, algorithms, AI models, trademarks, service marks, logos, trade dress, and all intellectual property rights therein (collectively, "Company IP") are owned by or licensed to the Company and are protected by copyright, trademark, patent, trade secret, and other intellectual property laws of the United Kingdom, foreign jurisdictions, and international conventions. Except for the limited license granted to you in Section 10.3, no right, title, or interest in any Company IP is transferred to you.</p>
              <p>10.2 <strong>Trademarks:</strong> "BA Work XP™," "BA WorkXP™," and all related logos, product and service names, designs, and slogans are trademarks of the Company or its affiliates or licensors. You may not use such marks without the prior written permission of the Company. All other names, logos, product and service names, designs, and slogans mentioned in the Services are the trademarks of their respective owners.</p>
              <p>10.3 <strong>Limited License to Users:</strong> Subject to your strict compliance with these Terms, the Company grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Services solely for your personal, non-commercial educational purposes during your active Subscription Period. This license does not include any right to: (a) copy, modify, create derivative works from, distribute, or publicly display any Content except as expressly permitted; (b) use any data mining, robots, scraping, or similar data gathering methods; (c) download (other than page caching) or modify the Services or any portion thereof; (d) attempt to gain unauthorized access to any portion of the Services; or (e) use the Services for any purpose other than as expressly intended.</p>
              <p>10.4 <strong>User Content License to Company:</strong> By submitting, uploading, posting, or transmitting User Content through the Services, you grant the Company a worldwide, non-exclusive, royalty-free, fully paid, sublicensable, and transferable license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display such User Content in connection with operating, providing, improving, and marketing the Services. This license continues even after you stop using the Services to the extent necessary for the Company's business operations, legal compliance, and service provision to other users.</p>
              <p>10.5 <strong>Feedback:</strong> If you provide any ideas, suggestions, feedback, or recommendations regarding the Services ("Feedback"), you grant the Company a worldwide, perpetual, irrevocable, royalty-free license to use, disclose, and exploit such Feedback for any purpose without compensation or attribution to you.</p>
              <p>10.6 <strong>DMCA Policy:</strong> The Company respects intellectual property rights and expects users to do the same. If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement, please provide our copyright agent with the following information in accordance with the Digital Millennium Copyright Act (DMCA): (a) identification of the copyrighted work claimed to have been infringed; (b) identification of the allegedly infringing material; (c) your contact information; (d) a statement that you have a good faith belief that use of the material is not authorized by the copyright owner; (e) a statement that the information is accurate and, under penalty of perjury, you are authorized to act on behalf of the owner; and (f) your physical or electronic signature. Send DMCA notices to support@baworkxp.com.</p>
            </div>
          </section>

          {/* 11. FEES, PAYMENTS, AND FINANCIAL TERMS */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">11. FEES, PAYMENTS, BILLING, AND REFUNDS (COMPREHENSIVE)</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>11.1 <strong>Fee Structure:</strong> Current fees are set forth in Section 6.4 of these Terms. All fees are in British Pounds Sterling (£ GBP) unless otherwise stated. Fees may include but are not limited to: Subscription fees, renewal fees, add-on services, premium features, device change processing fees, late payment fees, and administrative fees.</p>
              <p>11.2 <strong>Payment Authorization:</strong> By providing payment information and completing a purchase, you authorize the Company and its payment processors to charge the payment method provided for all applicable fees. You represent and warrant that you have the legal right to use the payment method provided and that all payment information is accurate and current. You agree to promptly update payment information if it changes.</p>
              <p>11.3 <strong>Payment Processing:</strong> Payments are processed by third-party payment processors subject to their terms and conditions. The Company is not responsible for errors or delays caused by payment processors. Your payment information is handled in accordance with PCI DSS standards and our Privacy Policy.</p>
              <p>11.4 <strong>Failed Payments:</strong> If a payment fails for any reason (insufficient funds, expired card, bank decline, etc.): (a) your access to the Services may be immediately suspended; (b) you will be notified via email; (c) you will have seven (7) days to update payment information and complete the transaction; (d) if payment is not received within seven (7) days, your Account may be terminated and all access permanently revoked; (e) you remain liable for all outstanding fees plus any collection costs, late fees, and interest.</p>
              <p>11.5 <strong>Late Fees:</strong> Any fees not paid when due shall accrue interest at a rate of 1.5% per month (18% per annum) or the maximum rate permitted by law, whichever is lower, from the due date until paid in full. You shall also be responsible for all costs of collection, including reasonable attorneys' fees.</p>
              <p>11.6 <strong>Taxes:</strong> All fees are exclusive of applicable taxes (VAT, GST, sales tax, etc.). You are responsible for all taxes. If the Company is required to collect or pay taxes, such taxes will be added to your invoice. You agree to provide any tax identification numbers or tax exemption certificates requested by the Company.</p>
              <p>11.7 <strong>Price Changes:</strong> The Company reserves the right to change fees at any time with or without notice. Price changes apply to new purchases and renewals immediately upon posting of new prices. Active paid Subscriptions continue at the original price until expiration. Continued use after price changes constitutes acceptance of new prices.</p>
              <p>11.8 <strong>No Refunds Except as Stated:</strong> ALL FEES ARE NON-REFUNDABLE except as expressly provided in Section 7. There are no pro-rated refunds for early termination, reduced usage, dissatisfaction, or any other reason outside of the 14-day refund window described in Section 7.</p>
              <p>11.9 <strong>Disputed Charges:</strong> If you dispute a charge, you must contact support@baworkxp.com within thirty (30) days of the charge. The Company will investigate and respond within a reasonable time. Initiating chargebacks without first attempting to resolve the matter with the Company constitutes a breach of these Terms and may result in Account termination and legal action.</p>
              <p>11.10 <strong>Currency Conversion:</strong> If your payment method or bank converts the transaction to a different currency, you acknowledge that conversion rates and foreign transaction fees are determined by your bank and payment processor. The Company is not responsible for such rates or fees.</p>
            </div>
          </section>

          {/* 12. RESERVATION OF RIGHTS */}
          <section className="bg-yellow-50 border-l-4 border-yellow-600 pl-3 py-2">
            <h2 className="font-bold text-yellow-900 text-[11px] mb-2 uppercase">12. COMPANY'S RESERVATION OF RIGHTS</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>12.1 The Company expressly reserves the following rights, which may be exercised at any time, in the Company's sole and absolute discretion, with or without prior notice, with or without cause, and without liability to you or any third party:</p>
              <p className="ml-3">(a) <strong>Modify Services:</strong> To modify, update, enhance, reduce, limit, or change any aspect of the Services, including features, functionality, Content, design, user interface, performance specifications, or availability;</p>
              <p className="ml-3">(b) <strong>Discontinue Services:</strong> To discontinue, suspend, or terminate the Services or any portion thereof, temporarily or permanently, for any reason or no reason, including for maintenance, upgrades, technical issues, business reasons, or legal compliance;</p>
              <p className="ml-3">(c) <strong>Refuse Service:</strong> To refuse service, deny access, or decline to process registrations or renewals for any person or entity, for any reason or no reason, without explanation;</p>
              <p className="ml-3">(d) <strong>Remove Content:</strong> To remove, edit, modify, or refuse to post any User Content or Company Content at any time, for any reason, without notice;</p>
              <p className="ml-3">(e) <strong>Suspend or Terminate Accounts:</strong> To suspend, restrict, or permanently terminate any Account at any time, for any reason or no reason, including for suspected violations of these Terms, suspicious activity, fraud, or as required by law;</p>
              <p className="ml-3">(f) <strong>Impose Limits:</strong> To impose limits on certain features or restrict access to parts or all of the Services without notice and without liability;</p>
              <p className="ml-3">(g) <strong>Monitor Activity:</strong> To monitor, record, and log all user activity, communications, and interactions with the Services for any purpose, including security, compliance, quality assurance, and improvement;</p>
              <p className="ml-3">(h) <strong>Change Terms:</strong> To modify, amend, update, or replace these Terms at any time as described in Section 14;</p>
              <p className="ml-3">(i) <strong>Change Fees:</strong> To change, increase, or decrease fees and pricing at any time as described in Section 11;</p>
              <p className="ml-3">(j) <strong>Assign Rights:</strong> To assign, transfer, or delegate any of our rights or obligations under these Terms to any third party;</p>
              <p className="ml-3">(k) <strong>Cooperate with Authorities:</strong> To cooperate with law enforcement, government agencies, courts, and regulatory bodies, including disclosing user information when legally required or when we believe in good faith such disclosure is appropriate;</p>
              <p className="ml-3">(l) <strong>Use User Data:</strong> To use, analyze, and process user data as described in our Privacy Policy and these Terms, including for AI training, analytics, and service improvement;</p>
              <p className="ml-3">(m) <strong>Enforce Policies:</strong> To enforce these Terms, investigate violations, take remedial action, and pursue all available legal remedies;</p>
              <p className="ml-3">(n) <strong>Maintain Discretion:</strong> To exercise discretion in all matters related to the Services, user accounts, and enforcement of these Terms.</p>
              <p className="mt-2">12.2 Exercise of any of these reserved rights does not create any liability or obligation on the part of the Company, and you waive any claims arising from the Company's exercise of these rights. The Company's failure to exercise any reserved right does not constitute a waiver of that right.</p>
              <p>12.3 YOU ACKNOWLEDGE AND AGREE THAT THE COMPANY MAY CEASE OFFERING OR PROVIDING ANY SERVICES AT ANY TIME WITH OR WITHOUT PRIOR NOTICE, AND THE COMPANY SHALL HAVE NO LIABILITY TO YOU OR ANY THIRD PARTY FOR SUCH CESSATION, INCLUDING NO OBLIGATION TO PROVIDE REFUNDS (EXCEPT AS PROVIDED IN SECTION 7).</p>
            </div>
          </section>

          {/* 13. DISCLAIMERS */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">13. DISCLAIMERS OF WARRANTIES</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>13.1 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED ON AN "AS IS," "AS AVAILABLE," AND "WITH ALL FAULTS" BASIS. THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES, CONDITIONS, REPRESENTATIONS, AND GUARANTEES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO:</p>
              <p className="ml-3">(a) IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, QUIET ENJOYMENT, OR ARISING FROM COURSE OF DEALING OR USAGE OF TRADE;</p>
              <p className="ml-3">(b) ANY WARRANTIES REGARDING AVAILABILITY, ACCURACY, RELIABILITY, TIMELINESS, COMPLETENESS, SECURITY, LACK OF ERRORS, OR UNINTERRUPTED OPERATION OF THE SERVICES;</p>
              <p className="ml-3">(c) ANY WARRANTIES REGARDING THE QUALITY, ACCURACY, RELIABILITY, OR APPROPRIATENESS OF AI-GENERATED OUTPUT;</p>
              <p className="ml-3">(d) ANY WARRANTIES THAT DEFECTS, ERRORS, OR BUGS WILL BE CORRECTED;</p>
              <p className="ml-3">(e) ANY WARRANTIES REGARDING RESULTS, OUTCOMES, EMPLOYMENT, CERTIFICATION, OR SUCCESS ARISING FROM USE OF THE SERVICES;</p>
              <p className="ml-3">(f) ANY WARRANTIES THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS.</p>
              <p>13.2 THE COMPANY DOES NOT WARRANT THAT: (a) THE SERVICES WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE; (b) ANY DEFECTS OR ERRORS WILL BE CORRECTED; (c) THE SERVICES ARE FREE OF VIRUSES OR HARMFUL COMPONENTS; OR (d) ANY PARTICULAR RESULTS WILL BE ACHIEVED.</p>
              <p>13.3 NO ORAL OR WRITTEN INFORMATION, ADVICE, OR REPRESENTATION PROVIDED BY THE COMPANY OR ITS REPRESENTATIVES CREATES ANY WARRANTY. YOU USE THE SERVICES ENTIRELY AT YOUR OWN RISK.</p>
            </div>
          </section>

          {/* 14. LIMITATION OF LIABILITY */}
          <section className="bg-red-50 border-l-4 border-red-600 pl-3 py-2">
            <h2 className="font-bold text-red-900 text-[11px] mb-2 uppercase">14. LIMITATION OF LIABILITY AND DAMAGES WAIVER</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>14.1 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, LICENSORS, OR SERVICE PROVIDERS (COLLECTIVELY, "COMPANY PARTIES") BE LIABLE TO YOU OR ANY THIRD PARTY FOR:</p>
              <p className="ml-3">(a) ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOST PROFITS, LOST REVENUE, LOST SAVINGS, LOST DATA, BUSINESS INTERRUPTION, LOSS OF GOODWILL, LOSS OF OPPORTUNITY, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES;</p>
              <p className="ml-3">(b) ANY DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE SERVICES;</p>
              <p className="ml-3">(c) ANY DAMAGES ARISING FROM ERRORS, MISTAKES, INACCURACIES, OR OMISSIONS IN CONTENT OR OUTPUT;</p>
              <p className="ml-3">(d) ANY DAMAGES ARISING FROM UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA OR COMMUNICATIONS;</p>
              <p className="ml-3">(e) ANY DAMAGES ARISING FROM SUSPENSION, TERMINATION, OR MODIFICATION OF THE SERVICES;</p>
              <p className="ml-3">(f) ANY DAMAGES ARISING FROM VIRUSES, MALWARE, OR HARMFUL CODE TRANSMITTED THROUGH THE SERVICES;</p>
              <p className="ml-3">(g) ANY DAMAGES ARISING FROM THIRD-PARTY CONTENT, SERVICES, OR CONDUCT.</p>
              <p>14.2 THE COMPANY'S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES, WHETHER IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO THE COMPANY IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO LIABILITY, OR ONE HUNDRED POUNDS STERLING (£100), WHICHEVER IS GREATER.</p>
              <p>14.3 THESE LIMITATIONS APPLY REGARDLESS OF THE LEGAL THEORY UPON WHICH DAMAGES ARE SOUGHT (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE), EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
              <p>14.4 SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN WARRANTIES OR DAMAGES. IN SUCH JURISDICTIONS, THE ABOVE EXCLUSIONS AND LIMITATIONS SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
            </div>
          </section>

          {/* 15. INDEMNIFICATION */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">15. INDEMNIFICATION</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>15.1 You agree to indemnify, defend, and hold harmless the Company Parties from and against any and all claims, demands, actions, suits, proceedings, liabilities, damages, losses, costs, and expenses (including reasonable attorneys' fees and court costs) arising out of or relating to:</p>
              <p className="ml-3">(a) Your use or misuse of the Services;</p>
              <p className="ml-3">(b) Your violation of these Terms;</p>
              <p className="ml-3">(c) Your violation of any rights of any third party, including intellectual property rights, privacy rights, or proprietary rights;</p>
              <p className="ml-3">(d) Your User Content, Input, or any content you submit, post, or transmit through the Services;</p>
              <p className="ml-3">(e) Your violation of any applicable laws, rules, or regulations;</p>
              <p className="ml-3">(f) Any false, inaccurate, misleading, or fraudulent information you provide;</p>
              <p className="ml-3">(g) Your negligence, willful misconduct, or breach of fiduciary duty;</p>
              <p className="ml-3">(h) Any activity conducted under your Account, whether or not authorized by you.</p>
              <p>15.2 The Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of such claims. You will not settle any claim that affects the Company without the Company's prior written consent. This indemnification obligation survives termination of these Terms and your use of the Services.</p>
            </div>
          </section>

          {/* 16. DISPUTE RESOLUTION AND ARBITRATION */}
          <section className="bg-purple-50 border-l-4 border-purple-600 pl-3 py-2">
            <h2 className="font-bold text-purple-900 text-[11px] mb-2 uppercase">16. DISPUTE RESOLUTION, ARBITRATION, AND CLASS ACTION WAIVER</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>16.1 <strong>Informal Resolution:</strong> Prior to initiating any formal dispute resolution proceeding, you agree to first contact the Company at support@baworkxp.com to attempt to resolve any dispute, claim, or controversy arising out of or relating to these Terms or the Services (each a "Dispute") informally. You agree to negotiate in good faith for a period of thirty (30) days to attempt to reach an amicable resolution. If the Dispute is not resolved within thirty (30) days, either party may pursue formal resolution as described below.</p>
              <p>16.2 <strong>Binding Arbitration:</strong> Any Dispute that cannot be resolved informally shall be finally and exclusively resolved by binding arbitration administered by the London Court of International Arbitration (LCIA) under its rules then in effect, except as modified by this Section 16. The arbitration shall be conducted in London, England, in the English language, before a single arbitrator appointed in accordance with LCIA rules. The arbitrator's decision shall be final and binding on the parties and may be entered as a judgment in any court of competent jurisdiction.</p>
              <p>16.3 <strong>Arbitration Procedures:</strong> The arbitrator shall have exclusive authority to resolve any Dispute, including but not limited to disputes regarding the scope, enforceability, or arbitrability of this Section 16, except that only a court of competent jurisdiction may decide issues relating to the enforceability of the class action waiver in Section 16.5. The arbitrator shall apply substantive law consistent with the UK Arbitration Act 1996 and shall honor claims of privilege recognized at law. The arbitrator may award damages, declaratory relief, or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party's individual claim. The arbitrator may not consolidate more than one person's claims or otherwise preside over any form of representative or class proceeding.</p>
              <p>16.4 <strong>Costs of Arbitration:</strong> Each party shall bear its own costs and attorneys' fees in arbitration, except that the Company will pay all LCIA filing, administration, and arbitrator fees for any arbitration initiated in accordance with this Section 16, unless the arbitrator finds that the substance of your Dispute or the relief sought was frivolous or brought for an improper purpose, in which case the arbitrator may award fees and costs in accordance with applicable law.</p>
              <p>16.5 <strong>CLASS ACTION WAIVER:</strong> YOU AND THE COMPANY AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION. YOU AND THE COMPANY EXPRESSLY WAIVE ANY RIGHT TO PURSUE CLASS ARBITRATION, CLASS ACTION, OR ANY CONSOLIDATED OR REPRESENTATIVE PROCEEDING. If a court or arbitrator determines that this class action waiver is unenforceable, then the arbitration agreement in this Section 16 shall be null and void, and any Disputes shall be resolved in court as provided in Section 17.</p>
              <p>16.6 <strong>Exceptions to Arbitration:</strong> Notwithstanding the above, either party may: (a) seek equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation, or violation of intellectual property rights; (b) bring an action in small claims court if the claim qualifies and remains in such court; and (c) seek injunctive relief to enforce the terms of this arbitration agreement, including the class action waiver.</p>
              <p>16.7 <strong>Opt-Out Right:</strong> You have the right to opt out of this arbitration agreement by sending written notice of your decision to opt out to support@baworkxp.com within thirty (30) days of first accepting these Terms or any subsequent changes to this Section 16. Your notice must include your name, email address, and a clear statement that you wish to opt out of this arbitration agreement. If you opt out, you and the Company will not be bound by this Section 16, but all other terms of this Agreement will continue to apply.</p>
              <p>16.8 <strong>Survival:</strong> This Section 16 shall survive termination of these Terms and your use of the Services.</p>
            </div>
          </section>

          {/* 17. GOVERNING LAW AND JURISDICTION */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">17. GOVERNING LAW, JURISDICTION, AND VENUE</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>17.1 <strong>Governing Law:</strong> These Terms and any Dispute arising out of or related to these Terms or the Services shall be governed by and construed in accordance with the laws of England and Wales, without regard to its conflict of law provisions. The United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transactions Act shall not apply.</p>
              <p>17.2 <strong>Jurisdiction and Venue:</strong> Subject to the arbitration provisions in Section 16, you irrevocably agree that the courts of England and Wales shall have exclusive jurisdiction to settle any Dispute or claim arising out of or in connection with these Terms or the Services. You irrevocably waive any objection to venue in such courts on grounds of inconvenient forum or otherwise.</p>
              <p>17.3 <strong>Waiver of Jury Trial:</strong> TO THE EXTENT PERMITTED BY LAW, YOU AND THE COMPANY WAIVE ANY RIGHT TO A TRIAL BY JURY IN ANY PROCEEDING ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES.</p>
            </div>
          </section>

          {/* 18. MODIFICATIONS TO TERMS */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">18. MODIFICATIONS AND UPDATES TO TERMS</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>18.1 The Company reserves the right to modify, amend, update, or replace any part of these Terms at any time, in its sole discretion, with or without prior notice. Changes may be made for any reason, including but not limited to: legal compliance, business changes, feature updates, security improvements, or policy refinements.</p>
              <p>18.2 We will notify you of material changes by: (a) posting the updated Terms on our website with a new "Last Updated" date; (b) sending email notification to the address associated with your Account; or (c) displaying a prominent notice on the Services. For non-material changes, posting on the website may be the sole notice provided.</p>
              <p>18.3 Continued use of the Services after changes take effect constitutes your acceptance of the modified Terms. If you do not agree to the modified Terms, your sole remedy is to discontinue use of the Services and terminate your Account. You will not receive a refund if you terminate due to Terms modifications (except within the 14-day refund window for new purchases).</p>
              <p>18.4 It is your responsibility to review these Terms periodically. You should check the "Last Updated" date at the top of these Terms to see when they were last revised.</p>
            </div>
          </section>

          {/* 19. MISCELLANEOUS */}
          <section>
            <h2 className="font-bold text-gray-900 text-[11px] mb-2 uppercase">19. GENERAL PROVISIONS AND MISCELLANEOUS TERMS</h2>
            <div className="space-y-1 ml-2 text-[9px]">
              <p>19.1 <strong>Entire Agreement:</strong> These Terms, together with our Privacy Policy and any other policies or guidelines incorporated by reference, constitute the entire agreement between you and the Company regarding the Services and supersede all prior or contemporaneous understandings, agreements, representations, and warranties, whether written or oral.</p>
              <p>19.2 <strong>Severability:</strong> If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court or arbitrator, such provision shall be modified and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions shall continue in full force and effect.</p>
              <p>19.3 <strong>Waiver:</strong> No waiver by the Company of any term or condition of these Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition. Any failure by the Company to assert a right or provision under these Terms shall not constitute a waiver of such right or provision.</p>
              <p>19.4 <strong>Assignment:</strong> You may not assign, transfer, or delegate your rights or obligations under these Terms without the Company's prior written consent. The Company may freely assign, transfer, or delegate its rights and obligations under these Terms without restriction, including in connection with a merger, acquisition, reorganization, or sale of assets. Any purported assignment by you in violation of this Section shall be null and void.</p>
              <p>19.5 <strong>No Third-Party Beneficiaries:</strong> These Terms do not confer any third-party beneficiary rights. No person or entity not a party to these Terms shall have any right to enforce any term of these Terms.</p>
              <p>19.6 <strong>Force Majeure:</strong> The Company shall not be liable for any failure or delay in performing its obligations under these Terms due to causes beyond its reasonable control, including but not limited to: acts of God, natural disasters, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, pandemics, strikes, labor disputes, internet or telecommunications failures, power outages, or failures of third-party service providers.</p>
              <p>19.7 <strong>Notices:</strong> All notices required or permitted under these Terms must be in writing and shall be deemed delivered when: (a) delivered by hand; (b) sent by registered or certified mail, postage prepaid, return receipt requested; or (c) sent by email with confirmation of receipt. Notices to you may be sent to the email address associated with your Account. Notices to the Company must be sent to support@baworkxp.com.</p>
              <p>19.8 <strong>Relationship of Parties:</strong> The relationship between you and the Company is that of independent contractors. Nothing in these Terms shall be construed as creating any agency, partnership, joint venture, employment, or franchis relationship between you and the Company.</p>
              <p>19.9 <strong>Language:</strong> These Terms are prepared and executed in the English language, which shall be the controlling language in all respects. Any translation is provided for convenience only.</p>
              <p>19.10 <strong>Interpretation:</strong> The headings and captions in these Terms are for convenience only and shall not affect the interpretation of these Terms. The terms "including," "includes," and "include" mean "including without limitation." The word "or" is not exclusive. References to "writing" include email and electronic communications.</p>
              <p>19.11 <strong>Survival:</strong> All provisions of these Terms which by their nature should survive termination shall survive, including but not limited to: ownership provisions, warranty disclaimers, indemnity, limitations of liability, dispute resolution, and miscellaneous provisions.</p>
            </div>
          </section>

          {/* FINAL ACCEPTANCE */}
          <section className="bg-red-600 text-white p-4 mt-6">
            <h2 className="font-bold text-[12px] mb-2 uppercase">ACKNOWLEDGMENT AND ACCEPTANCE</h2>
            <p className="text-[10px] leading-snug">
              BY CLICKING "I ACCEPT," "I AGREE," "SIGN UP," OR ANY SIMILAR BUTTON, OR BY ACCESSING OR USING THE SERVICES IN ANY MANNER, YOU ACKNOWLEDGE THAT: (1) YOU HAVE READ THESE TERMS IN THEIR ENTIRETY; (2) YOU UNDERSTAND THESE TERMS; (3) YOU AGREE TO BE BOUND BY THESE TERMS; (4) YOU HAVE HAD THE OPPORTUNITY TO SEEK INDEPENDENT LEGAL ADVICE; (5) YOU SPECIFICALLY ACKNOWLEDGE AND AGREE TO THE ACCOUNT SHARING PROHIBITION IN SECTION 4, THE DEVICE BINDING REQUIREMENTS IN SECTION 5, AND THE REFUND LIMITATIONS IN SECTION 7; AND (6) THESE TERMS CONSTITUTE A LEGAL AND BINDING AGREEMENT BETWEEN YOU AND BA WORK XP LIMITED.
            </p>
          </section>

          {/* Contact */}
          <section className="bg-gray-50 p-3 mt-4">
            <p className="font-bold text-[10px] mb-1">CONTACT INFORMATION</p>
            <p className="text-[9px]">BA Work XP Limited | support@baworkxp.com | United Kingdom</p>
            <p className="text-[9px] mt-1 text-gray-600">For all inquiries including legal questions, refund requests, or account issues, contact support@baworkxp.com. Response time: 24-48 hours for all inquiries.</p>
          </section>

        </div>
      </div>
    </div>
  );
};

export default TermsOfServiceView;
