// Export all types
export * from './meeting';
export * from './chat';

// AppView type definition
export type AppView = 
  | 'welcome'
  | 'get-started'
  | 'dashboard'
  | 'learn'
  | 'learning-hub'
  | 'learning-flow'
  | 'practice-flow'
  | 'project-flow'
  | 'project-journey'
  | 'core-learning'
  | 'project-initiation'
  | 'stakeholder-mapping'
  | 'module-3-stakeholder-mapping'
  | 'stakeholder-conversations-flow'
  | 'elicitation'
  | 'requirements-engineering'
  | 'documentation'
  | 'my-resources'
  | 'career-journey'
  | 'solution-options'
  | 'design-hub'
  | 'mvp-hub'
  | 'agile-scrum'
  | 'practice'
  | 'practice-2'
  | 'documentation-practice'
  | 'mvp-practice'
  | 'hands-on-project'
  | 'elicitation-hub'
  | 'motivation'
  | 'community-hub'
  | 'project'
  | 'core-concepts'
  | 'agile-scrum'
  | 'scrum-essentials'
  | 'scrum-learning'
  | 'scrum-practice'
  | 'agile-practice'
  | 'progress-tracking'
  | 'project-workspace'
  | 'meeting-history'
  | 'portfolio'
  | 'create-project'
  | 'ba-fundamentals'
  | 'process-mapper'
  | 'ai-process-mapper'
  | 'process-mapper-editor'
  | 'diagram-creation'
  | 'advanced-topics'
  | 'projects'
  | 'project-setup'
  | 'meeting'
  | 'voice-only-meeting'
  | 'voice-meeting-v2'
  | 'meeting-summary'
  | 'meeting-details'
  | 'raw-transcript'
  | 'notes'
  | 'deliverables'
  | 'profile'
  | 'support'
  | 'navigation-guide'
  | 'analysis'
  | 'ba-in-action-understanding-context'
  | 'ba-in-action-stakeholder-communication'
  | 'ba-in-action-discovery-elicitation'
  | 'ba-in-action-analysis-spotting-issues'
  | 'ba-in-action-to-be-and-solution-shaping'
  | 'ba-in-action-working-with-developers'
  | 'ba-in-action-uat-validation'
  | 'ba-in-action-continuous-improvement'
  | 'custom-project'
  | 'custom-stakeholders'
  | 'agile-hub'
  | 'elevenlabs-meeting'
  | 'individual-agent-meeting'
  | 'enhanced-training-flow'
  | 'training-hub'
  | 'training-hub-project-selection'
  | 'training-hub-stage-selection'
  | 'practice-hub-cards'
  | 'training-practice'
  | 'training-assess'
  | 'training-feedback'
  | 'training-dashboard'
  | 'training-deliverables'
  | 'project-deliverables'
  | 'my-meetings'
  | 'voice-meeting'
  | 'voice-meeting-simple'
  | 'settings'
  | 'project-brief'
  | 'stage-selection'
  | 'stakeholders'
  | 'meeting-mode-selection'
  | 'structured-training'
  | 'pre-brief'
  | 'live-training-meeting'
  | 'post-brief'
  | 'user-story-checker'
  | 'solution-options'
  | 'design-hub'
  | 'mvp-hub'
  | 'mvp-engine'
  | 'community-hub'
  | 'community-admin'
  | 'my-mentorship'
  | 'book-session'
  | 'mentor-feedback'
  | 'career-coaching'
  | 'my-progress-mentor'
  | 'admin'
  | 'admin-panel'
  | 'contact-us'
  | 'admin-contact-submissions'
  | 'faq'
  | 'my-cohort'
  | 'admin-cohorts';

// Re-export specific types for convenience
export type {
  Message,
  DirectMessage,
  UserProfile,
  MessageThread,
  PinnedMessage,
  TypingIndicator,
  SearchResult,
  Conversation,
  Channel,
  MessageReaction,
  SearchResponse,
  ConversationListResponse,
  UserProfileResponse
} from './chat';